name: Invio Quotazioni e Meteo

on:
  schedule:
    # Pianificato per le 08:00 UTC (le 10:00 in Italia)
    - cron: '0 8 * * *' 
  workflow_dispatch: # Ti permette di fare i test manuali

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configurazione Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installazione dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pyTelegramBotAPI requests

      - name: Esecuzione script Finanza
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tracker.py

      - name: Esecuzione script Meteo
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python meteo.py
